language: python

python:
  - 3.3
  - 3.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz

# Install packages
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls pydot lxml

# Run test
script:
  - coverage run setup.py test

after_success:
  - coveralls
